### ISSUE TITLE
Doesnt work with cache-disabled: false

### ISSUE THREAD

**Issue by spamnick** [amyu/setup-android#145]
```
sdk-version: 30
build-tools-version: 30.0.3
ndk-version: 
cmake-version: 
cache-disabled: false
```
Full steps
```
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    - name: Setup JDK
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: '17'
#        cache: 'gradle'

    - name: Setup Android SDK
      uses: amyu/setup-android@v2
      with:
        # default: false
        # Whether to use the cache
        cache-disabled: false

        # default: '30'
        # sdk version
        # see https://developer.android.com/studio/releases/platforms
        # It will always be installed.
        sdk-version: '30'

        # default: '30.0.3'
        # build tools version
        # see https://developer.android.com/studio/releases/build-tools
        # It will always be installed.
        build-tools-version: '30.0.3'

        # default: ''
        # cmake version
        # see https://developer.android.com/studio/projects/install-ndk
        # Installed when the version is specified
        # cmake-version: '3.10.2.4988404'

        # default: ''
        # cmake version
        # see https://developer.android.com/studio/projects/install-ndk
        # Installed when the version is specified
        # ndk-version: '23.1.7779620'

        # default: true
        # Whether to generate or not the job summary
        # generate-job-summary: false

```
Result:
https://i.imgur.com/DCJJNR0.png

But if set cache-disabled: true , then it works fine:
https://i.imgur.com/VDRisEs.png
