### ISSUE TITLE
Error: SdkManagerCli has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by annuh** [amyu/setup-android#159]
Hi!

I'm trying to use this action on a self-hosted macOS runner, that runs via [Tartelet](https://github.com/shapehq/tartelet).

However, executing this action triggers the following error:
```
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

This is our workflow:
```yaml
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11' # Recommended by React Native (07-09-2023)
          cache: 'gradle'

      - name: Setup Android SDK
        uses: amyu/setup-android@v3
```

Complete log:
```
Run amyu/setup-android@v3
  with:
    sdk-version: 33
    build-tools-version: 33.0.2
    cache-disabled: false
    generate-job-summary: true
    job-status: success
  env:
    JAVA_HOME: /Users/runner/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/11.0.20-101/arm64/Contents/Home
    JAVA_HOME_11_ARM64: /Users/runner/actions-runner/_work/_tool/Java_Temurin-Hotspot_jdk/11.0.20-101/arm64/Contents/Home
sdk-version:33
build-tools-version: 33.0.2
ndk-version: 
cmake-version: 
cache-disabled: false
Not Found cache
downloading cmdline-tools ...
/usr/bin/unzip -o -q /Users/runner/actions-runner/_work/_temp/c7104969-492f-4717-b841-e226a1ba181c
downloaded cmdline-tools
installing ...
/bin/bash -c yes | sdkmanager --licenses --sdk_root=/Users/runner/.android/sdk
Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Error: The process '/bin/bash' failed with exit code 1
```

Did someone encounter this issue before or knows a way to fix this? Thanks! 🙂

**Comment by amyu** [comment]
👀

**Comment by amyu** [comment]
@annuh 
Thanks for issue.
I tried the same settings and reproduced it. ↓ 
https://github.com/amyu/setup-android/pull/160
https://github.com/amyu/setup-android/actions/runs/6111398932/job/16586549240?pr=160

I don't have it all figured out yet, but I think it's probably due to a low JDK version.

**Comment by amyu** [comment]
@annuh

https://github.com/amyu/setup-android/actions/runs/6111523745/job/16586953871?pr=160
It worked.
I recommend JDK version 17.

or 

You can use amyu/setup-android@v2.
V2 works with a lower version of cmdline-tools and therefore a lower version of JDK.
```
      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11' # Recommended by React Native (07-09-2023)
          cache: 'gradle'

      - name: Setup Android SDK
        uses: amyu/setup-android@v2 // <- here!!!!!!!
```
