### ISSUE TITLE
cmdline-tools : could not determine SDK root

### ISSUE THREAD

**Issue by wtto00** [amyu/setup-android#167]
See this: https://9to5answer.com/cmdline-tools-could-not-determine-sdk-root

Please place `cmdline-tools` under the `ANDROID_HOME` directory, with the following directory structure: `$ANDROID_HOME/cmdline-tools/latest/bin/avdmanager`.

**Comment by amyu** [comment]
:eyes:

**Comment by amyu** [comment]
Hi @wtto00 !
Thanks issue.

Under what conditions does this Issue occur?

**Comment by wtto00** [comment]
Hello, thank you for your reply.

I would like to start an emulator in CI. Please wait a moment while I write an example to reproduce it.

**Comment by wtto00** [comment]
When installing an SDK, I must add the parameter `--sdk_root` otherwise it will throw an error `could not determine SDK root`.

```yml
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sdkmanager --install "system-images;android-31;default;x86_64"
          avdmanager -s create avd --name Android_Emulator --package "system-images;android-31;default;x86_64"
          $ANDROID_HOME/emulator/emulator -list-avds
          $ANDROID_HOME/emulator/emulator -verbose -avd Android_Emulator
```
---
When I added the `--sdk-root` parameter, the SDK installation was successful.

But how do I use the installed SDK?

When I use `avdmanager -s create avd --name SomeName --package "system-images;android-31;default;x86_64"`, it shows an error `Error: Package path is not valid. Valid system image paths are: null`.

The demo: https://github.com/wtto00/demo-setup-android/actions/runs/6212159784
