### ISSUE TITLE
Getting error while setting up action

### ISSUE THREAD

**Issue by slice-saransh-gupta** [amyu/setup-android#191]
getting error 
`Unable to locate executable file: unzip. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

<img width="1323" alt="Screenshot 2023-10-12 at 12 10 56 AM" src="https://github.com/amyu/setup-android/assets/137060837/376cfa6a-904d-460a-a3a8-fceab88672e8">

steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.3
        with:
          sdk-version: '33'
          build-tools-version: '30.0.3'

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

**Comment by amyu** [comment]
eyes
im sorry
i can't resolve now, because igo on vacation
please wait 3 days🥹

is your self hosted runner Linux? Or windows?

**Comment by slice-saransh-gupta** [comment]
its linux

**Comment by amyu** [comment]
@slice-saransh-gupta 
https://github.com/amyu/setup-android/pull/194
https://github.com/amyu/setup-android/actions/runs/6493084052/job/17633298502

```
  test_191:
    name: run check issue 191
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: remove android sdk from ubuntu-latest
        shell: bash
        run: |
          echo 'ANDROID_HOME=' >> $GITHUB_ENV
          echo 'ANDROID_SDK_ROOT=' >> $GITHUB_ENV
          rm -rf ~/android

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.3
        with:
          cache-disabled: true
          sdk-version: '33'
          build-tools-version: '30.0.3'

      - name: Build gradle project
        run: ./sample-android-project/gradlew -p sample-android-project build
```

I added a test in the same environment
But I could not reproduce the above problem.
Can you give me some more clues?
Is this a constant problem?
