### ISSUE TITLE
cache-disabled to true runs always the post step 

### ISSUE THREAD

**Issue by dinisnunes1** [amyu/setup-android#25]
I'm using the action with `cache-disabled: true`, but the **Post step** which runs after my build step is always taking ~2 minutes (even if the cache is disabled).
<img width="815" alt="disabled_cache_post_step" src="https://user-images.githubusercontent.com/12532273/223150312-7512c900-7743-457b-b2b9-45bdc1a58adf.png">

Here is a sample of how i'm setting up the action:
```
- name: Setup JDK 11
  uses: actions/setup-java@v3
  with:
    java-version: 11
    distribution: temurin

- name: Setup Android SDK
  uses: amyu/setup-android@v2
  with:
    cache-disabled: true
    sdk-version: '31'
    build-tools-version: '30.0.2'
    ndk-version: '21.3.6528147'

- name: Build
  run: ./gradlew assembleRelease --stacktrace
 
```

It looks that it's caching anyway?
